### ISSUE TITLE
Pocketbase built for ARM only

### ISSUE THREAD

**Issue by smrdotgg** [xyntechx/ezMCQ#1]
The pocketbase binary found in '/backend/pocketbase' is built for ARM, so it won't work for most computers that aren't M1/M2 macbooks.

Including an x86 build of the binary should fix it I think.

This is what happens when I ran it on an intel laptop.

![image](https://user-images.githubusercontent.com/49459061/229029408-bf1d9aba-95f5-4f88-a139-c69ecc942d87.png)

**Comment by xyntechx** [comment]
Hi! Thanks a lot for the feedback! I've included the executables for each OS and updated the README with the updated usage instructions.

**Comment by smrdotgg** [comment]
Yep, its working now. :blush: 

 Closing the Issue.
